### ISSUE TITLE
Tomes can't be crafted

### ISSUE THREAD

**Issue by SengeeSama** [hanskroner/tomes-of-experience#28]
When trying to craft a tome, you can't, there's no result.
Minecraft version 1.21.1
![image](https://github.com/user-attachments/assets/9a5096ac-5ecf-4063-b68f-6c9b52a86d57)
![image](https://github.com/user-attachments/assets/449e7acd-ea48-4422-8965-9836035eab8c)

**Comment by SengeeSama** [comment]
Is it possible to make the tomes compatible with flat level curves? Like a config option to input the XP value for a level. Personally I have a level curve where all levels are worth 50 XP and I'd like to have XP storage that doesn't break for this like Global XP does :(
This seemed like a nice alternative but it doesn't seem to be working very well with custom level curves.

**Comment by hanskroner** [comment]
@SengeeSama  - Thanks for taking the time to report this. I'd forgotten to include updates to the `recipe` datapack.

I'd be happy to look into making the tomes work with flat level curves. Would you mind opening a separate issue for that where we can discuss?
