### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by alvlasov** [hanskroner/tomes-of-experience#30]
Hi!

I made a russian tranlation for your mod. Currently as a resoource pack. Could you integrate it inside the mod?

[tomes-of-experience-0.0.4-ru.zip](https://github.com/user-attachments/files/17243300/tomes-of-experience-0.0.4-ru.zip)

**Comment by hanskroner** [comment]
Thanks for contributing this translation! I'll put it into the mod with the next release

**Comment by alvlasov** [comment]
Thank you! If you add some more text in the next release, you can ask me to translate.

**Comment by hanskroner** [comment]
Implemented in #32
