### ISSUE TITLE
Flat level curve support?

### ISSUE THREAD

**Issue by SengeeSama** [hanskroner/tomes-of-experience#31]
Is it possible to make the tomes compatible with flat level curves? Like a config option to input the XP value for a level. Personally I have a level curve where all levels are worth 50 XP and I'd like to have XP storage that doesn't break for this like Global XP does :(
This seemed like a nice alternative but it doesn't seem to be working very well with custom level curves.

**Comment by hanskroner** [comment]
Today, the tomes transfer percentages of an experience level assuming the game follows [this level curve](https://minecraft.fandom.com/wiki/Experience#Leveling_up).

It would be possible to add additional curves, but it might be nicer to follow curves that have been defined elsewhere. How are you defining your flat, 50 XP level curve? Is it through another mod?

**Comment by SengeeSama** [comment]
Yes, I'm defining my curve through the mod Fixed Levels by neptunecentury which allows any flat XP per level amount as config option

**Comment by hanskroner** [comment]
Implemented in #33
